name: Deploy Raylib Project to GitHub Pages

on:
  push:
    branches: [ main ] # Cambia a 'master' si es el nombre de tu rama principal

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Emscripten
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 3.1.64 # Versión recomendada estable

    - name: Configure CMake (Web)
      # Usamos los mismos flags que tienes en tu tasks.json
      run: |
        mkdir build-web
        cd build-web
        emcmake cmake .. -DPLATFORM=Web -DCMAKE_BUILD_TYPE=Release

    - name: Build Project
      run: |
        cd build-web
        make # En GitHub Actions (Linux) usamos make por defecto

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build-web