name: Deploy Raylib Project to GitHub Pages

on:
  push:
    branches: [ main ] # Verifica si tu rama es 'main' o 'master'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Ninja
      run: sudo apt-get install -y ninja-build

    - name: Install Emscripten
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 3.1.64

    - name: Configure CMake (Web)
      # Usamos Ninja para coincidir con tu configuración local
      run: |
        mkdir build-web
        cd build-web
        emcmake cmake .. -DPLATFORM=Web -G Ninja -DCMAKE_BUILD_TYPE=Release

    - name: Build Project
      run: |
        cd build-web
        ninja

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build-web